name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la public || echo "No public directory"
          cat firebase.json || echo "No firebase.json file"
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Firebase debug info
        run: firebase --version
      
      - name: Deploy to Firebase with verbose logging
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --debug --non-interactive
